repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Specify the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3.9  # Change to your Python version

  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args: [--remove-all-unused-imports, --remove-duplicate-keys, --remove-unused-variables, --in-place, --remove-unused-variables]
